export const userInputs = [
    {
        id: 1,
        label: "Username",
        type: "text",
        placeholder: "john_doe",
    },
    {
        id: 2,
        label: "Name and surname",
        type: "text",
        placeholder: "John Doe",
    },
    {
        id: 3,
        label: "Email",
        type: "mail",
        placeholder: "john_doe@gmail.com",
    },
    {
        id: 4,
        label: "Phone",
        type: "text",
        placeholder: "+1 234 567 89",
    },
    {
        id: 5,
        label: "Password",
        type: "password",
    },
    {
        id: 6,
        label: "Address",
        type: "text",
        placeholder: "Elton St. 216 NewYork",
    },
    {
        id: 7,
        label: "Country",
        type: "text",
        placeholder: "USA",
    },
];

export const productInputs = [
    {
        id: 1,
        name: "name",
        label: "Nombre",
        type: "text",
        placeholder: "Batería 12x75 Baja",
        errorMessage: "Debe ingresar un nombre de producto válido",
        required: true,
        pattern: `/^[a-zA-Z0-9]{1,40}$/`,
    },
    {
        id: 2,
        name: "brand",
        label: "Marca",
        type: "text",
        placeholder: "Bernal",
        errorMessage: "Debe ingresar un nombre de marca válido",
        required: true,
        pattern: `/^[a-zA-Z0-9]{1,40}$/`,
    },
    {
        id: 3,
        name: "model",
        label: "Modelo",
        type: "text",
        placeholder: "UF12S32",
        errorMessage: "Debe ingresar un modelo de producto válido",
        required: false,
        pattern: `/^[a-zA-Z0-9]{1,40}$/`,
    },
    {
        id: 4,
        name: "price",
        label: "Pricio",
        type: "number",
        placeholder: "100.21",
        errorMessage: "Debe ingresar un precio válido",
        required: true,
        pattern: `/^.*$/i`,
    },
    {
        id: 5,
        name: "description",
        label: "Descripción",
        type: "text",
        placeholder:
            "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
        errorMessage: "Debe ingresar un precio válido",
        required: true,
        pattern: `/^\S.{19,}$/`,
    },
    {
        id: 6,
        name: "origins",
        label: "Origen",
        type: "text",
        placeholder: "ARG",
        errorMessage: "Debe ingresar un origen válido",
        required: true,
        pattern: ` /^[a-zA-Z0-9\s]{1,10}$/`,
    },
    {
        id: 7,
        name: "maintenanceFree",
        label: "Libre Mantenimiento",
        type: "checkbox",
        placeholder: "",
    },
    {
        id: 8,
        name: "waranty",
        label: "Meses de Garantía",
        type: "number",
        placeholder: "12",
        errorMessage: "Debe ingresar un valor numérico entero para la garantía",
        required: true,
        pattern: `/^[0-9]+$/`,
    },
    {
        id: 9,
        name: "voltage",
        label: "Voltaje",
        type: "number",
        placeholder: "12",
        errorMessage: "Debe ingresar un valor numérico entero para el voltaje",
        required: false,
        pattern: `/^[0-9]+$/`,
    },
    {
        id: 10,
        name: "capacity",
        label: "Capacidad",
        type: "number",
        placeholder: "65",
        errorMessage:
            "Debe ingresar un valor numérico entero para la capacidad",
        required: false,
        pattern: `/^[0-9]+$/`,
    },
    {
        id: 11,
        name: "height",
        label: "Altura en centímetros",
        type: "number",
        placeholder: "38.45",
        errorMessage: "Debe ingresar un valor numérico para la altura",
        required: false,
        pattern: `/(?:(?!-)[0-9])+/`,
    },
    {
        id: 12,
        name: "width",
        label: "Ancho en centímetros",
        type: "number",
        placeholder: "41.85",
        errorMessage: "Debe ingresar un valor numérico para el ancho",
        required: false,
        pattern: `/^[0-9]+$/`,
    },
    {
        id: 13,
        name: "length",
        label: "Profundidad en centímetros",
        type: "number",
        placeholder: "15.60",
        errorMessage: "Debe ingresar un valor numérico para la profundidad",
        required: false,
        pattern: `/^[0-9]+$/`,
    },
    {
        id: 14,
        name: "stock",
        label: "Cant. en stock",
        type: "number",
        placeholder: "10",
        errorMessage: "Debe ingresar un valor numérico entero para el stock",
        required: true,
        pattern: `/^[0-9]+$/`,
    },
    {
        id: 15,
        name: "categories",
        label: "Categorías separadas por comas",
        type: "text",
        placeholder: "Baterías, Cargadores, Agua Destilada",
        errorMessage: "Debe ingresar al menos una categoría",
        required: true,
        pattern: `/^[\w\s]{1,40}$/`,
    },
    {
        id: 16,
        name: "isActive",
        label: "Producto Activo",
        type: "checkbox",
        placeholder: "",
    },
];

export const vehicleInputs = [
    {
        id: 1,
        name: "brand",
        label: "Marca",
        type: "text",
        placeholder: "Ford",
    },
    {
        id: 2,
        name: "model",
        label: "Modelo",
        type: "text",
        placeholder: "F-150",
    },
    {
        id: 3,
        name: "engine",
        label: "Motor",
        type: "number",
        placeholder: "3.5",
    },
    {
        id: 4,
        name: "year",
        label: "Año",
        type: "text",
        placeholder: "2010",
    },
    {
        id: 5,
        name: "type",
        label: "Tipo",
        type: "text",
        placeholder: "Auto",
    },
];
